#!/usr/bin/env python3
"""Regenerate services/sim2real-web/board-camera-frames.mjs fixtures.

12 synthetic 640x480 JPEG frames (moving duck over a grid floor) used by the
local host-station reference BoardAgent to simulate a board camera feed. Real
deployments replace the agent camera source; this fixture keeps the demo
offline and deterministic. Run with python3 + Pillow.
"""
import base64, io, math
from PIL import Image, ImageDraw

W, H = 640, 480
N_FRAMES = 12
TARGET = 'services/sim2real-web/board-camera-frames.mjs'

frames = []
for k in range(N_FRAMES):
    img = Image.new('RGB', (W, H), (12, 20, 34))
    d = ImageDraw.Draw(img)
    for gx in range(0, W, 64):
        d.line([(gx, H - 140), (W // 2 + (gx - W // 2) // 4, H - 8)], fill=(28, 44, 66), width=1)
    for gy in range(8, 133, 24):
        d.line([(0, H - 140 + gy), (W, H - 140 + gy)], fill=(20, 32, 50), width=1)
    t = k / N_FRAMES
    x = 40 + (W - 140) * (0.5 - 0.5 * math.cos(2 * math.pi * t))
    y = 300 - 60 * math.sin(math.pi * t * 2)
    d.rectangle([x, y, x + 80, y + 60], fill=(255, 190, 60), outline=(255, 220, 120), width=2)
    d.rectangle([x + 10, y - 26, x + 46, y + 2], fill=(255, 230, 150))
    d.rectangle([0, 0, W, 28], fill=(7, 16, 26))
    d.text((10, 8), f"RDK X5 board camera (synthetic fixture) frame {k:02d}", fill=(104, 227, 255))
    buf = io.BytesIO()
    img.save(buf, 'JPEG', quality=72)
    frames.append(buf.getvalue())

lines = [
    '// AUTO-GENERATED by scripts/generate-board-camera-frames.py. Do not edit by hand.',
    '// 12 synthetic JPEG frames (640x480) simulating a board camera feed for the',
    '// local host-station reference agent. Real deployments replace this with the',
    '// board MJPEG/WebSocket camera stream; see docs/host-station.md.',
    'export const BOARD_CAMERA_FIXTURE_FRAMES = [',
]
for f in frames:
    lines.append('  Buffer.from(' + repr(base64.b64encode(f).decode()) + ", 'base64'),")
lines.append('];')
with open(TARGET, 'w') as fp:
    fp.write('\n'.join(lines) + '\n')
print('wrote', TARGET, 'frames:', len(frames))
