#!/usr/bin/env node
/**
 * Regenerates every engine's pinned dependency lock.
 *
 * The engines' libraries were previously installed with unpinned
 * `pip install --user numpy torch onnx`-style commands, which means a training
 * run could not be reproduced once the environment moved on: `sourceCommit`
 * names the code, but nothing named the libraries. Each engine now carries a
 * `requirements.in` (direct dependencies, hand-edited) and a `requirements.txt`
 * (the full transitive pin plus hashes, generated). This script owns the second
 * file.
 *
 * `uv` is required and is a *development* tool, not a runtime dependency of the
 * platform or the engines: the engines keep running on whatever Python the
 * operator already has, and the lock is what makes that environment
 * reproducible. Hashes are generated so a locked install is verifiable.
 *
 * Usage:
 *   node scripts/lock-engines.mjs            # regenerate every lock
 *   node scripts/lock-engines.mjs --check    # fail if a lock is out of date
 */
import { spawnSync } from 'node:child_process';
import { copyFileSync, existsSync, readFileSync, renameSync } from 'node:fs';
import { mkdtempSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const ENGINES = [
  'starter-ppo',
  'mjx-adapter',
  'mjlab-rsl-rl-adapter',
  'microduck-eval',
  'microduck-recurrent',
  'offline-bc',
  'act',
  'diffusion-policy',
  'smolvla',
  // A CLI format tool, not a training engine — but its pyarrow/numpy pins
  // deserve the same reproducible-lock treatment as the engines.
  'lerobot-converter',
];
const check = process.argv.includes('--check');

/**
 * uv writes its cache outside the workspace by default, which fails under a
 * restricted sandbox. A workspace-local cache keeps the command runnable
 * wherever the repository is checked out.
 */
function uvEnvironment() {
  return { ...process.env, UV_CACHE_DIR: path.join(ROOT, '.data', 'uv-cache') };
}

function uvAvailable() {
  return spawnSync('uv', ['--version'], { encoding: 'utf8' }).status === 0;
}

function compile(source, target) {
  return spawnSync('uv', ['pip', 'compile', source, '-o', target, '--generate-hashes', '--quiet'], {
    encoding: 'utf8',
    cwd: ROOT,
    env: uvEnvironment(),
  });
}

/**
 * Drops uv's autogenerated header, whose `-o` line embeds the output path. That
 * path differs between the committed file and a `--check` scratch file, so
 * comparing raw text would report every lock as stale.
 */
function lockBody(text) {
  return text
    .split('\n')
    .filter(
      (line) =>
        !line.startsWith('# This file was autogenerated') &&
        !line.startsWith('#    uv pip compile'),
    )
    .join('\n')
    .trim();
}

function packageCount(text) {
  return text.split('\n').filter((line) => /^[a-z0-9]/.test(line)).length;
}

const missing = ENGINES.filter(
  (engine) => !existsSync(path.join(ROOT, 'engines', engine, 'requirements.in')),
);
if (missing.length) {
  console.error(`[lock-engines] FAIL — missing requirements.in for: ${missing.join(', ')}`);
  process.exit(1);
}
if (!uvAvailable()) {
  // A missing development tool is a SKIP for --check (CI may not install uv) but
  // a hard failure when the operator explicitly asked to regenerate.
  console.log(
    `[lock-engines] ${check ? 'SKIP' : 'FAIL'} — uv is not installed (https://docs.astral.sh/uv/)`,
  );
  process.exit(check ? 0 : 1);
}

const scratch = mkdtempSync(path.join(os.tmpdir(), 'lock-engines-'));
try {
  const stale = [];
  for (const engine of ENGINES) {
    const source = path.join('engines', engine, 'requirements.in');
    const target = path.join('engines', engine, 'requirements.txt');
    const targetPath = path.join(ROOT, target);
    // Always compile into scratch: uv keeps versions from an existing output
    // file when they still satisfy the constraints, so compiling straight
    // onto the committed lock would freeze every transitive pin forever and
    // disagree with --check (which necessarily compiles from scratch).
    const output = path.join(scratch, `${engine}.txt`);
    const run = compile(source, output);
    if (run.status !== 0) {
      console.error(`[lock-engines] FAIL — ${engine}: ${(run.stderr || '').trim()}`);
      process.exit(1);
    }
    if (check) {
      const fresh = readFileSync(output, 'utf8');
      const committed = existsSync(targetPath) ? readFileSync(targetPath, 'utf8') : '';
      if (lockBody(committed) !== lockBody(fresh)) stale.push(engine);
      else
        console.log(`[lock-engines] ${engine}: lock is current (${packageCount(fresh)} packages)`);
    } else {
      // Stage inside the target directory so the final rename is atomic on
      // one filesystem (scratch lives in os.tmpdir(), possibly another volume).
      const staged = `${targetPath}.tmp`;
      copyFileSync(output, staged);
      renameSync(staged, targetPath);
      const written = readFileSync(targetPath, 'utf8');
      console.log(`[lock-engines] ${engine}: wrote ${target} (${packageCount(written)} packages)`);
    }
  }
  if (stale.length) {
    console.error(
      `[lock-engines] FAIL — stale lock(s): ${stale.join(', ')}. Run: node scripts/lock-engines.mjs`,
    );
    process.exit(1);
  }
  if (check) console.log('[lock-engines] OK — every engine lock matches its requirements.in');
} finally {
  rmSync(scratch, { recursive: true, force: true });
}
